---
apiVersion: v1
kind: Template
metadata:
  name: integreatly-cronjob-backup-template
  annotations:
    description: 'Cronjob for backing up integreatly data'
objects:
  - apiVersion: authorization.openshift.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: backupjob
    roleRef:
      name: backupjob
    subjects:
      - kind: ServiceAccount
        name: backupjob
        namespace: ${SA_NAMESPACE}
parameters:
  - name: SA_NAMESPACE
    description: Namespace of the ServiceAccount to bind
    value: default
    required: true
